# Generated by Django 2.0.4 on 2018-04-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EB_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Экспортируемая база - App',
                'verbose_name_plural': 'Экспортируемая база - App',
            },
        ),
        migrations.CreateModel(
            name='EB_Data_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('app_id', models.CharField(blank=True, max_length=128, null=True)),
                ('local_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_App')),
            ],
            options={
                'verbose_name': 'Экспортируемая база - Data_App',
                'verbose_name_plural': 'Экспортируемая база - Data_App',
            },
        ),
        migrations.CreateModel(
            name='EB_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Экспортируемая база - Order',
                'verbose_name_plural': 'Экспортируемая база - Order',
            },
        ),
        migrations.CreateModel(
            name='EB_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Экспортируемая база - Place',
                'verbose_name_plural': 'Экспортируемая база - Place',
            },
        ),
        migrations.CreateModel(
            name='EB_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Экспортируемая база - Session',
                'verbose_name_plural': 'Экспортируемая база - Session',
            },
        ),
    ]
