# Generated by Django 2.0.4 on 2018-04-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0002_ef_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='EF_Link_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_load', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='file_for_export_link_data/')),
            ],
            options={
                'verbose_name': 'Файл для экспорта - Link_Data',
                'verbose_name_plural': 'Файл для экспорта - Link_Data',
            },
        ),
        migrations.CreateModel(
            name='EF_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_load', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='file_for_export_orders/')),
            ],
            options={
                'verbose_name': 'Файл для экспорта - Orders',
                'verbose_name_plural': 'Файл для экспорта - Orders',
            },
        ),
    ]
