# Generated by Django 2.0.4 on 2018-04-13 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0003_ef_link_data_ef_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='EB_App_Ul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id_unic', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Экспортируемая база - App_Unic_ID',
                'verbose_name_plural': 'Экспортируемая база - App_Unic_ID',
            },
        ),
        migrations.AlterField(
            model_name='eb_data_app',
            name='app_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_App_Ul'),
        ),
    ]
