# Generated by Django 2.0.4 on 2018-04-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0004_auto_20180413_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='eb_app_ul',
            name='local_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_App'),
        ),
    ]
