# Generated by Django 2.0.4 on 2018-04-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0005_eb_app_ul_local_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='EB_Data_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_App_Ul')),
                ('app_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_App')),
            ],
            options={
                'verbose_name': 'Экспортируемая база - Data_Link',
                'verbose_name_plural': 'Экспортируемая база - Data_Link',
            },
        ),
        migrations.AddField(
            model_name='eb_place',
            name='place_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='eb_session',
            name='session_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='eb_place',
            name='local_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_Data_Link'),
        ),
        migrations.AddField(
            model_name='eb_session',
            name='local_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_Data_Link'),
        ),
    ]
