# Generated by Django 2.0.4 on 2018-04-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0007_auto_20180414_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_EB_App_Ul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id_unic', models.CharField(blank=True, max_length=128, null=True)),
                ('local_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_App')),
            ],
            options={
                'verbose_name': 'Обработанная база - App_Unic_ID',
                'verbose_name_plural': 'Обработанная база - App_Unic_ID',
            },
        ),
        migrations.CreateModel(
            name='New_EB_Data_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('app_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.New_EB_App_Ul')),
                ('local_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_App')),
            ],
            options={
                'verbose_name': 'Обработанная база - Data_App',
                'verbose_name_plural': 'Обработанная база - Data_App',
            },
        ),
        migrations.CreateModel(
            name='New_EB_Data_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.New_EB_App_Ul')),
                ('app_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_App')),
            ],
            options={
                'verbose_name': 'Обработанная база - Data_Link',
                'verbose_name_plural': 'Обработанная база - Data_Link',
            },
        ),
        migrations.CreateModel(
            name='New_EB_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id_unic', models.CharField(blank=True, max_length=128, null=True)),
                ('revenue', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Обработанная база - Order',
                'verbose_name_plural': 'Обработанная база - Order',
            },
        ),
        migrations.CreateModel(
            name='New_EB_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, max_length=128, null=True)),
                ('local_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.New_EB_Data_Link')),
            ],
            options={
                'verbose_name': 'Обработанная база - Place',
                'verbose_name_plural': 'Обработанная база - Place',
            },
        ),
        migrations.CreateModel(
            name='New_EB_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=128, null=True)),
                ('local_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.New_EB_Data_Link')),
            ],
            options={
                'verbose_name': 'Обработанная база - Session',
                'verbose_name_plural': 'Обработанная база - Session',
            },
        ),
        migrations.AddField(
            model_name='new_eb_order',
            name='session_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.New_EB_Session'),
        ),
    ]
