# Generated by Django 2.0.4 on 2018-04-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0008_auto_20180416_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_EB_Sinhronisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinhronisation', models.CharField(blank=True, max_length=128, null=True)),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.New_EB_Order')),
            ],
            options={
                'verbose_name': 'Обработанная база - Sinhronisation',
                'verbose_name_plural': 'Обработанная база - Sinhronisation',
            },
        ),
    ]
