# Generated by Django 2.0.4 on 2018-04-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0009_new_eb_sinhronisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_eb_sinhronisation',
            old_name='sinhronisation',
            new_name='order_id_unic',
        ),
        migrations.RemoveField(
            model_name='new_eb_sinhronisation',
            name='order',
        ),
        migrations.AddField(
            model_name='new_eb_sinhronisation',
            name='old_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_Order'),
        ),
    ]
