# Generated by Django 2.0.4 on 2018-04-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0010_auto_20180417_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_eb_sinhronisation',
            name='sinhronis_ok',
            field=models.BooleanField(default=False),
        ),
    ]
