# Generated by Django 2.0.4 on 2018-04-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0011_new_eb_sinhronisation_sinhronis_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_eb_order',
            name='key_for_data',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.New_EB_Data_App'),
        ),
    ]
