# Generated by Django 2.0.4 on 2018-04-17 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0012_new_eb_order_key_for_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_00', models.BooleanField(default=False)),
                ('h_01', models.BooleanField(default=False)),
                ('h_02', models.BooleanField(default=False)),
                ('h_03', models.BooleanField(default=False)),
                ('h_04', models.BooleanField(default=False)),
                ('h_05', models.BooleanField(default=False)),
                ('h_06', models.BooleanField(default=False)),
                ('h_07', models.BooleanField(default=False)),
                ('h_08', models.BooleanField(default=False)),
                ('h_09', models.BooleanField(default=False)),
                ('h_10', models.BooleanField(default=False)),
                ('h_11', models.BooleanField(default=False)),
                ('h_12', models.BooleanField(default=False)),
                ('h_13', models.BooleanField(default=False)),
                ('h_14', models.BooleanField(default=False)),
                ('h_15', models.BooleanField(default=False)),
                ('h_16', models.BooleanField(default=False)),
                ('h_17', models.BooleanField(default=False)),
                ('h_18', models.BooleanField(default=False)),
                ('h_19', models.BooleanField(default=False)),
                ('h_20', models.BooleanField(default=False)),
                ('h_21', models.BooleanField(default=False)),
                ('h_22', models.BooleanField(default=False)),
                ('h_23', models.BooleanField(default=False)),
                ('app', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_App')),
                ('app_data', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.New_EB_Data_App')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.New_EB_Order')),
            ],
            options={
                'verbose_name': 'Анализ - активные часы',
                'verbose_name_plural': 'Анализ - активные часы',
            },
        ),
    ]
