# Generated by Django 2.0.4 on 2018-04-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0013_active_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_hour',
            name='h_00',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_01',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_02',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_03',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_04',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_05',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_06',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_07',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_08',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_09',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_10',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_11',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_12',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_13',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_14',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_15',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_16',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_17',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_18',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_19',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_20',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_21',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_22',
        ),
        migrations.RemoveField(
            model_name='active_hour',
            name='h_23',
        ),
        migrations.AddField(
            model_name='active_hour',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
