# Generated by Django 2.0.4 on 2018-04-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0014_auto_20180418_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Анализ - активные дни',
                'verbose_name_plural': 'Анализ - активные дни',
            },
        ),
        migrations.RenameField(
            model_name='active_hour',
            old_name='active',
            new_name='active_hour',
        ),
        migrations.AddField(
            model_name='active_hour',
            name='active_day',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.Active_Day'),
        ),
    ]
