# Generated by Django 2.0.4 on 2018-04-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0015_auto_20180418_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_of_the_week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(blank=True, max_length=20, null=True)),
                ('med_speed', models.FloatField(default=0)),
                ('app', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.EB_App')),
            ],
            options={
                'verbose_name': 'Анализ - дни недели',
                'verbose_name_plural': 'Анализ - дни недели',
            },
        ),
        migrations.AddField(
            model_name='active_day',
            name='day_of_the_week',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.Day_of_the_week'),
        ),
        migrations.AddField(
            model_name='active_hour',
            name='day_of_the_week',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_data.Day_of_the_week'),
        ),
    ]
