# Generated by Django 2.0.4 on 2018-04-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0016_auto_20180418_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_day',
            name='day_of_the_week',
        ),
    ]
