# Generated by Django 2.0.4 on 2018-04-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0017_remove_active_day_day_of_the_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Hour_Reload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_hour', models.IntegerField(default=0)),
                ('summa', models.IntegerField(default=0)),
            ],
        ),
    ]
