# Generated by Django 2.0.4 on 2018-04-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0018_active_hour_reload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Active_Hour_Reload',
        ),
    ]
